#!/bin/bash
echo "the public ip address is :"
dig +short myip.opendns.com @resolver1.opendns.com
echo "the private ip address is :"
ifconfig wlan0 |grep netmask | awk -F "inet " {'print $2'} | cut -d ' ' -f1

